name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour
    - cron: '1 7 * * 2'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Ryoferzz/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/channel/UC9ppbV54mFWroWbS6fFZuEw"